### ISSUE TITLE
502 error accesing onlyoffice

### ISSUE THREAD

**Issue by vetka925** [Moomboh/docker-compose-nginx-letsencrypt-proxy-nextcloud-onlyoffice#1]
Hi!

I got 502 error accesing onlyoffice. 
I have specified VIRTUAL_HOST and when trying open it in browser or adding this address in ONLYOFFICE settings in Nextcloud I get 502 error.
Could you help me to figure out what is the problem?

**Comment by vetka925** [comment]
And what IP should I specify in nginx-proxy-letsencrypt/docker-compose.yml?

**Comment by Moomboh** [comment]
Hello,
I'm not sure if this configuration template still works, since it hasn't been update in years. But I can still try to help:

`VIRTUAL_HOST` must be a domain which is pointing to the IP of your host. The IP in `nginx-proxy-letsencrypt/docker-compose.yml` refers to the IP `0.0.0.0` in the `ports` entry. The default IP `0.0.0.0` tells Docker to bind the ports to all available IP addresses on your host. You can (and should for best practice) change this to the specific IP address from which your host is publicly reachable. Leaving the default `0.0.0.0` should also work though.

Maybe check if the domain you specify on `VIRTUAL_HOST` is actually pointing to the IP of your host. Other than that, there could be various things causing this: Firewall, host network config, other services running on host or simply the fact that the config in this repo doesn't work with recent versions of onlyoffice anymore.

If you just want to have the onlyoffice editors integrated in your Nextcloud, there is an easiere way: https://nextcloud.com/blog/how-to-install-onlyoffice-in-nextcloud-hub-and-new-integration-feature/

Closing with this, since this is all I can offer in terms of help and I'm going to mark this repo as archived.
